Repository Team4-Kitcha/Kitcha-FE, pull requests merged in 2025-02, with the labels that each got.

#1 [Feat] LoginPage UI 구현
  eslint.config.js
  src/App.jsx
  src/assets/webps/common/rightArrowWhite.webp
  src/assets/webps/layout/logo.webp
  src/assets/webps/layout/prevBtn.webp
  src/assets/webps/login/ball1.webp
  src/assets/webps/login/ball2.webp
  src/assets/webps/login/balls.webp
  src/assets/webps/login/kitcha.webp
  src/assets/webps/login/rightArrowBlack.webp
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/components/ui/InputField.jsx
  src/pages/LoginPage.jsx
  src/pages/NotFoundPage.jsx
Labels: ♻️ Refactor, 🎨 Design, ✨ Feat

#2 [Feat] input placeholder 수정 & email 정규식 추가해서 로그인 버튼 활성화
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/components/ui/InputField.jsx
  src/pages/LoginPage.jsx
Labels: ✨ Feat

#3 [Feat] JoinPage UI 구현
  src/pages/JoinPage.jsx
Labels: 🎨 Design, ✨ Feat

#5 [Feat] MyPick 페이지 UI 구현
  src/assets/svgs/common/summary.svg
  src/assets/webps/news/summary.webp
  src/components/layout/Header.jsx
  src/components/mypick/Keyword.jsx
  src/constants/mypick/keywords.js
  src/constants/newslist/newsData.js
  src/pages/JoinPage.jsx
  src/pages/MyPickPage.jsx
  src/pages/NewsListPage.jsx
Labels: 🎨 Design, ✨ Feat

#6 [Feat] NewsDetail UI 구현 & NewsList 더미데이터 프로퍼티 명 수정
  src/assets/webps/news/mini_paper_clip.webp
  src/assets/webps/news/rectangle.webp
  src/assets/webps/news/solid_share.webp
  src/constants/newslist/newsData.js
  src/pages/NewsDetailPage.jsx
  src/pages/NewsListPage.jsx
Labels: 🎨 Design, ✨ Feat

#7 [Feat] Home 페이지 UI 구현
  src/assets/webps/home/ball1.webp
  src/assets/webps/home/ball2.webp
  src/assets/webps/home/ball3.webp
  src/assets/webps/home/ball4.webp
  src/assets/webps/home/deco.webp
  src/assets/webps/home/gatcha.webp
  src/assets/webps/home/rightArrowBlackBold.webp
  src/assets/webps/home/rightArrowWhiteBold.webp
  src/assets/webps/login/rightArrowWhite.webp
  src/assets/webps/news/rectangle.webp
  src/constants/newslist/newsData.js
  src/pages/HomePage.jsx
  src/pages/JoinPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPickPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsListPage.jsx
Labels: 🎨 Design, ✨ Feat

#8 [Feat] WritePage UI 구현 & Header, Layout 수정 - WritePage 업로드 버튼
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/pages/WritePage.jsx
Labels: ✨ Feat

#9 [Feat] Kitcha 페이지 UI 구현
  src/assets/webps/common/deco.webp
  src/assets/webps/home/gatchaTrans.webp
  src/assets/webps/kitcha/gatcha.webp
  src/components/layout/Header.jsx
  src/pages/HomePage.jsx
  src/pages/KitchaPage.jsx
Labels: 🎨 Design, ✨ Feat

#10 [Feat] Random 페이지 UI 구현
  src/assets/webps/random/bad.webp
  src/assets/webps/random/heart.webp
  src/constants/random/randomData.js
  src/pages/HomePage.jsx
  src/pages/KitchaPage.jsx
  src/pages/RandomPage.jsx
Labels: 🎨 Design, ✨ Feat

#11 Fix: cursor-pointer 제거
  src/pages/RandomPage.jsx
Labels: 🎨 Design

#12 [Feat] BoardDetail UI 구현
  src/assets/svgs/board/download.svg
  src/assets/svgs/board/pencil.svg
  src/assets/svgs/board/trash.svg
  src/assets/webps/board/paper_clip.webp
  src/pages/BoardDetailPage.jsx
Labels: 🎨 Design, ✨ Feat

#13 [Feat] Upload 페이지 UI 구현
  src/assets/webps/upload/plus.webp
  src/components/layout/Header.jsx
  src/pages/RandomPage.jsx
  src/pages/UploadPage.jsx
Labels: 🎨 Design, ✨ Feat

#14 [Feat] API instance 생성 & Login API 연결
  package-lock.json
  package.json
  src/apis/instance.js
  src/pages/LoginPage.jsx
  src/pages/MyPickPage.jsx
  src/pages/WritePage.jsx
Labels: 👽 API

#15 [Feat] BoardList UI 구현
  src/pages/BoardListPage.jsx
Labels: 🎨 Design, ✨ Feat

#16 [Feat] Join API 연결
  src/apis/instance.js
  src/constants/mypick/keywords.js
  src/pages/JoinPage.jsx
  src/pages/MyPickPage.jsx
Labels: 👽 API

#17 [Feat] Kitcha - MYPICK, RANDOM API 연결
  src/constants/random/randomData.js
  src/pages/KitchaPage.jsx
  src/pages/LoginPage.jsx
  src/pages/NewsListPage.jsx
  src/pages/RandomPage.jsx
Labels: 🐛 Bugfix, 👽 API

#18 [Feat] 파일 업로드 API 연결
  src/pages/UploadPage.jsx
Labels: 👽 API

#19 Feat: Modal 공통 컴포넌트 구현 및 아래 margin 설정
  src/apis/instance.js
  src/components/ui/Modal.jsx
  src/pages/HomePage.jsx
  src/pages/JoinPage.jsx
  src/pages/KitchaPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPickPage.jsx
  src/pages/RandomPage.jsx
  src/pages/UploadPage.jsx
Labels: ✨ Feat

#20 [Feat] BoardList api 연결 & StrictMode 제거
  src/main.jsx
  src/pages/BoardListPage.jsx
Labels: ✨ Feat, 👽 API

#23 [Fix] Write 수정일 때 업로드 버튼 명 변경 & 삭제 시 confirm modal
  src/components/layout/Header.jsx
  src/components/ui/ConfirmModal.jsx
  src/components/ui/Modal.jsx
  src/pages/BoardDetailPage.jsx
Labels: ✨ Feat

#24 [Refactor] useNavigate state 대신 sessionStorage로 뉴스 리스트 사용
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/main.jsx
  src/pages/BoardDetailPage.jsx
  src/pages/KitchaPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsListPage.jsx
  src/pages/RandomPage.jsx
  src/pages/UploadPage.jsx
  src/pages/WritePage.jsx
Labels: ♻️ Refactor, ✨ Feat

#25 [Fix] api url 수정 & header 대문자 Authorization
  src/pages/BoardDetailPage.jsx
  src/pages/BoardListPage.jsx
  src/pages/JoinPage.jsx
  src/pages/KitchaPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPickPage.jsx
  src/pages/RandomPage.jsx
  src/pages/UploadPage.jsx
  src/pages/WritePage.jsx
Labels: 🐛 Bugfix

#26 Fix: authorization으로 수정
  index.html
  src/apis/instance.js
  src/components/layout/Header.jsx
  src/pages/JoinPage.jsx
  src/pages/KitchaPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPickPage.jsx
  src/pages/NewsListPage.jsx
  src/pages/RandomPage.jsx
  src/pages/UploadPage.jsx
  src/pages/WritePage.jsx
  src/utils/decodeHtml.js
Labels: 🐛 Bugfix

#28 Fix: List 화면들 제목 말줄임 처리
  src/pages/BoardListPage.jsx
  src/pages/NewsListPage.jsx
Labels: 🎨 Design

#29 [Fix] Random 관심사 업데이트 sessionStorage 반영
  src/pages/RandomPage.jsx
Labels: 👽 API
